### ISSUE TITLE
Display correct version number

### ISSUE THREAD

**Issue by anis-marrouchi** [nooqta/kodyfire#6]
When running `kody -v`, the version that get displayed should be the one found in the [`package.json`](https://github.com/nooqta/kodyfire/blob/d5cf4bbf18033ca557973b86804048fc863d45c5/packages/kodyfire-cli/package.json ) file under kodyfire-cli package folder.
The version that gets displayed is now hard coded
https://github.com/nooqta/kodyfire/blob/d5cf4bbf18033ca557973b86804048fc863d45c5/packages/kodyfire-cli/src/bin/kody.ts#L8

**Comment by REX-HERE** [comment]
please assign this to me

**Comment by anis-marrouchi** [comment]
@REX-HERE any updates? Did you find your way?
