### ISSUE TITLE
Install and run kody

### ISSUE THREAD

**Issue by anis-marrouchi** [nooqta/kodyfire#7]
For first time contributors and hacktoberfest issues hunter
You are invited to follow the readme documentation and test out if the description is working as it is suppose too. If you find an issue feel free to file an issue. If your finding requires changes to the code, fork the repo, commit and push your changes after testing locally and do your Pull Request.

**Comment by abhishekganesan** [comment]
@anis-marrouchi Can you assign this to me?

**Comment by anis-marrouchi** [comment]
@abhishekganesan any updates?

**Comment by anis-marrouchi** [comment]
I'll unassign @abhishekganesan  you for now unless you are willing to collaborate

**Comment by abhishekganesan** [comment]
@anis-marrouchi I am working on this. I have installed the module locally and i was able to follow the instructions and scaffold different react components

**Comment by anis-marrouchi** [comment]
Ok great @abhishekganesan 
Can you check the publish command. Add instruction on what it is for and how to use. Report any issues if its not working as suppose to.

**Comment by abhishekganesan** [comment]
@anis-marrouchi 
I was able to successfully scaffold a new kody using this command `kody scaffold -n redux react`. redux-kodyfire got created. 
Did you want me to complete the kody by creating a concept and then publish it?

**Comment by abhishekganesan** [comment]
@anis-marrouchi Could you let me know?

**Comment by anis-marrouchi** [comment]
Hello @abhishekganesan yes sure, go ahead and publish your kody if that what you are asking for.
I was asking about the `kody publish `command which lets you overwrite the templates of a specfic kody, to test it and to check its working correclty
