### ISSUE TITLE
Review the readme

### ISSUE THREAD

**Issue by anis-marrouchi** [nooqta/kodyfire#8]
The readme file needs to be reviewed concerning the installation guide. We need to confirm kodyfire is working on all major OS as per the instructions in the readme. All suggestions are welcome. Please share theme here to discuss. Upon agreeing on what changes should be applied, you can fork the project add the changes and request PR.

**Comment by Chandak-Keshav** [comment]
Kindly assign me this @anis-marrouchi . I think I will be able to do this within a day or two.
